version: '3'

networks:
  nostr:
    enable_ipv6: true
    ipam:
      config:
        - subnet: fd00:db8:a::/64
          gateway: fd00:db8:a::1
services:
  # mint:
  #   image: cashubtc/nutshell:0.15.3
  #   container_name: mint
  #   ports:
  #     - "3338"
  #   networks:
  #     nostr:
  #   environment:
  #     - MINT_BACKEND_BOLT11_SAT=FakeWallet
  #     - MINT_LISTEN_HOST=0.0.0.0
  #     - MINT_LISTEN_PORT=3338
  #     - MINT_PRIVATE_KEY=TEST_PRIVATE_KEY
  #     - MINT_INFO_DESCRIPTION=This Cashu test mint has no public IP address and can only be reached via NWS powered by Nostr
  #     - MINT_INFO_NAME=Cashu NWS mint
  #   command: ["poetry", "run", "mint"]
  chamberlain:
    build: ../chamberlain
    container_name: chamberlain
    command:
      [
        "--network=regtest",
        "--bitcoind-rpc-url=http://host.docker.internal:18443",
        "--bitcoind-rpc-user=polaruser",
        "--bitcoind-rpc-password=polarpass",
        "--mint-url=http://chamberlain:3338",
        "--http-host=0.0.0.0",
        "--rpc-host=0.0.0.0",
        "--log-level=debug"
      ]
    ports:
      - "3338"
      - "3339"
    networks:
      nostr:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - chamberlain_data:/root/.chamberlain
  exit:
    build:
      context: .
      dockerfile: cmd/exit/Dockerfile
    container_name: exit
    networks:
      nostr:
    environment:
      - NOSTR_RELAYS=ws://nostr-relay:8080
      - NOSTR_PRIVATE_KEY=39f316139bdaffb708f48c803d7cc81eadb9b472860f9d323fdb79d68f323289
      - BACKEND_HOST=chamberlain:3339
  exit-https:
    build:
      context: .
      dockerfile: cmd/exit/Dockerfile
    container_name: exit-https
    command:
      [
        "./exit",
        "--port",
        "4443",
        "--target",
        "http://chamberlain:3338"
      ]
    networks:
      nostr:
    environment:
      - NOSTR_RELAYS=ws://nostr-relay:8080
      - NOSTR_PRIVATE_KEY=1a29483cafa686a08eda89e56dd9d1fc278aedacbbc385497bce00ec33d0d094
      - BACKEND_HOST=:4443
  entry:
    build:
      context: .
      dockerfile: cmd/entry/Dockerfile
    container_name: entry
    ports:
      - 8882:8882
    networks:
      nostr:
    environment:
      - NOSTR_RELAYS=ws://nostr-relay:8080
  nostr:
    image: scsibug/nostr-rs-relay:latest
    container_name: nostr-relay
    ports:
      - 8080:8080
    networks:
      nostr:
    restart: always
    volumes:
      - nostr_data:/usr/src/app/db
    user: 1000:1000

volumes:
  chamberlain_data:
  nostr_data:

